# Generated by Django 5.1.1 on 2024-10-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='interview',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='domain',
            field=models.CharField(choices=[('DSA', 'Data Structures'), ('Software Engineering', 'Software Engineering'), ('Web Development', 'Web Development')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='interview_type',
            field=models.CharField(choices=[('HR', 'HR'), ('technical', 'Technical'), ('managerial', 'Managerial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
    ]
