# Generated by Django 5.1.1 on 2024-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_question_interview_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.JSONField(default=list),
        ),
    ]
