# Generated by Django 5.1.1 on 2024-10-11 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_answer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_options',
        ),
    ]
