# Generated by Django 5.1.1 on 2024-10-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_question_answer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewpreference',
            old_name='type',
            new_name='interview_type',
        ),
        migrations.AlterField(
            model_name='interviewpreference',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='domain',
            field=models.CharField(choices=[('DSA', 'Data Structures'), ('Software Engineering', 'Software Engineering'), ('Web Development', 'Web Development')], default='medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='interview_type',
            field=models.CharField(choices=[('HR', 'HR'), ('technical', 'Technical'), ('managerial', 'Managerial')], default='Technical', max_length=50),
            preserve_default=False,
        ),
    ]
